language: perl
perl:
    - "5.8"
    - "5.8-thr"
    - "5.8.4"
    - "5.8.4-thr"
    - "5.8.8"
    - "5.8.8-thr"
    - "5.10"
    - "5.10-thr"
    - "5.12"
    - "5.12-thr"
    - "5.14"
    - "5.14-thr"
    - "5.16"
    - "5.16-thr"
    - "5.18"
    - "5.18-thr"
    - "5.20"
    - "5.20-thr"
    - "blead"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1           # enables coverage+coveralls reporting
  allow_failures:
    - perl: "blead"             # ignore failures for blead perl
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
    - cpan-install --deps       # installs prereqs, including recommends
    - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
    - coverage-setup
script:
    - prove -l -v $(test-dirs)   # parallel testing
after_success:
    - coverage-report
notifications:
    recipients:
    - ugexe@cpan.org
    email:
        on_success: change
        on_failure: always
